# Generated by Django 2.1.3 on 2018-12-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_icecream',
            old_name='picture',
            new_name='image',
        ),
    ]
